name: Build sources the run tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.20'

    - name: Install cpprestsdk
      run: sudo apt-get update && sudo apt-get install -y libcpprest-dev

    - name: Configure CMake
      run: cmake -DTEST=ON -B build

    - name: Build Google Test
      run: cmake --build build

    - name: Run Tests
      run: |
        cd build
        ctest -VV

